version: "3.8"

services:
  #Servicio DB (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: students_db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=students_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data 

  # Servicio Backend (FastAPI)
  api: 
    build: ./api
    container_name: students_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - ENV=development
      - DATABASE_URL=postgresql://root:password@db:5432/students_db
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  #Servicio Frontend (Vite + React)
  web:
    build: ./web
    container_name: students_front
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api

volumes:
  db_data: